- app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/27)
> Repair layout forcer to allow old class not at end of class list

- app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java
Here's the simple version. The downside is that there's no feedback whatsoever. So if the guy in PNG fat-fingers the json file or puts it in the wrong place, he won't know about it. I would be happy to add a little toast with a success message the first time the json file is read or an appropriate error message, if that sounds good.
Also, is there a good place in the repo to put a sample deviceId.json? Would that be helpful?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/56)
> BL-5083 Send custom device properties to Analytics

- app/src/main/java/org/sil/bloom/reader/ShelfActivity.java
- app/src/main/res/layout/app_bar_main.xml
- app/src/main/res/layout/content_main.xml
This backs out part of the previous change that added a shelf label, and updates the main toolbar to look like it. Along the way I realized that we need to ensure a contrasting foreground color in the heading, and did that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/63)
> BL-5098 only one heading for shelf view

- app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java
- app/src/main/res/values/strings.xml
During application onCreate, if there is no stored Device Id in the SharedPrefs, we check for a json file. If we succeed in parsing the file, there's a success toast. If we find a file but fail to parse it, there's a failure toast. Once device id metadata is loaded, we never look at the json again. This means changing the metadata requires a reinstall.
For the people loading the json file, once the file is transferred, they need to make sure BR is closed. Then they should run it and watch for the success message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/59)
> Success/Failure toasts for initial load of Device ID JSON.

- app/build.gradle
- app/proguard-rules.pro
A bunch of notes and warnings seem inseparable from using org.apache.commons:commons-compress:1.14. If we don't suppress them proguard crashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/68)
> BL-5199 Re-enable Proguard (with many problems suppressed)

- app/src/main/java/org/sil/bloom/reader/IOUtilities.java
- app/src/main/java/org/sil/bloom/reader/MainActivity.java
Here's the original PR: https://github.com/BloomBooks/BloomReader/pull/91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/93)
> [BL-5505] Recover from corrupted FileDescriptor during .bloombundle import

- app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
Sorry the last PR my fork acted really weird and scrubbed the correct code when I committed it and then kept the wrong stuff. Not sure what happened. 
Any rate give this a go. I'm not sure if clearing the cache at this point is the best solution, but it does seem to fix the problem on at least five separate devices. We also could not find any other adverse effects on any of the other features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/96)
> Fix for BL-5555 and caching images.

- app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
- app/src/main/res/layout/activity_reader.xml
- app/src/main/res/values-v21/styles.xml
https://issues.bloomlibrary.org/youtrack/issue/BL-5504
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/103)
> [BL-5504] Hide the status bar in the Reader Activity.

- app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/128)
> Auto advance and play animations even if there are no "audio-sentence" spans anywhere in the book (BL-5771)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sil/bloom/reader/BaseActivity.java
- app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java
- app/src/main/java/org/sil/bloom/reader/MainActivity.java
- app/src/main/java/org/sil/bloom/reader/SharingManager.java
- app/src/main/res/layout/app_bar_main.xml
- app/src/main/res/layout/blank.xml
- app/src/main/res/layout/need_storage_permission.xml
- app/src/main/res/layout/toolbar.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/filepaths.xml
- Bump target API to 26
- Request storage permissions at runtime
- Use a FileProvider for sharing files with a content URI rather than a regular File URI.
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/134)
> [BL-6445] Set Target API to 26 and make necessary updates

- app/src/main/java/org/sil/bloom/reader/MainActivity.java
- app/src/main/res/values/styles.xml
This makes the button color Bloom Red like in the other dialogs we have.
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/136)
> [BL-6521] Fix button color in the Delete Book/Shelf Dialog.

- app/src/main/java/org/sil/bloom/reader/BookFinderTask.java
- app/src/main/java/org/sil/bloom/reader/FileCleanupTask.java
- app/src/main/java/org/sil/bloom/reader/FileSearchState.java
- app/src/main/java/org/sil/bloom/reader/IOUtilities.java
- app/src/main/java/org/sil/bloom/reader/ImportBundleTask.java
- app/src/main/java/org/sil/bloom/reader/MainActivity.java
- app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
I want to test this some more before it gets merged, but here's a first look.
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6068
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/140)
> Better method for cleaning up files after importing books & bundles

- app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This doesn't seem to be the critical change to getting BL-6888 fixed.
That change is on the BloomPlayer side.
But this is still a good change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/158)
> Eliminate errors when stopping MediaPlayers (BL-6888)

- app/src/main/java/org/sil/bloom/reader/BookListAdapter.java
- app/src/main/java/org/sil/bloom/reader/SetBookListItemViewExtrasTask.java
- app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
- app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java
Fix the performance of the BookList by caching the value of hasAudio for a book and by performing slow operations asynchronously.
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6968
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/170)
> Performance fix

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sil/bloom/reader/MainActivity.java
The problem with the Samsung "My Files" app can be worked around by the
user.  If need be, we'll have to figure out how to explain it better than
my comments in the code and the issue indicated above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/172)
> Remove intent-filter that opened up too much (BL-7045)

- app/src/main/java/org/sil/bloom/reader/IOUtilities.java
- app/src/main/java/org/sil/bloom/reader/ImportBundleTask.java
See https://stackoverflow.com/questions/20080171/contentresolver-openfiledescriptor-does-not-call-contentprovider-openfile
for why these changes are needed and appropriate.  A similar change has
already been made to IOUtilities.copyBloomdFile(context, uri, toPath).
(This method used to be called copyFile, but is used only for copying
.bloomd files, so now has an added check in it.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/175)
> Remove unreliable file descriptor operations (BL-7073)

- app/proguard-rules.pro
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/206)
> Fix proguard-rules.pro to allow compilation of updated commons compress library (BL-7421)

- app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
- app/src/main/java/org/sil/bloom/reader/ReaderWebViewClient.java
* doesn't occur in 1.3 due to different arch. (no BP)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/211)
> BL-7567 prevent image caching between books

- app/src/main/java/org/sil/bloom/reader/BloomFileReader.java
Previously, index.htm was not found,  it was looking for mybook/.htm instead of mybook/mybook.htm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/236)
> BL-8617 fix bug in fallback search

- app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java
I don't see any other place to add this information to an analytics
event in Bloom Reader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/246)
> Add latitude, longitude, etc. to "Install Attributed" event (BL-8821)

- app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java
These are not currently useful and take up queue slots.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/251)
> Stop recording screen views

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sil/bloom/reader/MainActivity.java
- app/src/main/res/drawable/ic_baseline_usb_24.xml
- app/src/main/res/menu/activity_main_drawer.xml
- app/src/main/res/values/strings.xml
Anticipating Android 11, we add a menu option to "Receive books via USB", though for now it just shows a dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/253)
> Move to targeting Android 10, with legacy storage access

- app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/257)
> Add hardware "layer type" for webview to fix choppy video (BL-9727)

- app/src/main/java/org/sil/bloom/reader/IOUtilities.java
- app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
Note that the SAF code was already recursive
Does not treat folders as shelves
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/266)
> Load books from subdirectories as well as root (BL-10327)

- app/src/main/java/org/sil/bloom/reader/models/AlphanumComparator.java
- app/src/test/java/org/sil/bloom/reader/models/BookOrShelfTest.java
Note that Android < 7.0 will still use the old sort since ICU was introduced in Android in 7.0 (api 24).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/313)
> Use ICU sort for book titles in book list (BL-14289)
