app/src/main/res/layout/book_list_content.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/5)
=> Make list item width match parent (BL-4753)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/6)
=> Scale books to the device (BL-4752)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/WiFi/AcceptFileHandler.java, app/src/main/java/org/sil/bloom/reader/WiFi/AcceptNotificationHandler.java, app/src/main/java/org/sil/bloom/reader/WiFi/NewBookListenerService.java, app/src/main/java/org/sil/bloom/reader/WiFi/SyncServer.java, app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/7)
=> BL-4754 Connect over WiFi

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/8)
=> Make book always present as Device16x9Portrait (BL-4821)

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/9)
=> Refresh list (and notify) when a new book arrives (BL-4755)

app/src/main/java/org/sil/bloom/reader/models/Book.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/12)
=> Sort book list alphabetically (BL-4833)

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/13)
=> Optimize initial list load by sorting once

app/src/main/java/org/sil/bloom/reader/WiFi/NewBookListenerService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/14)
=> Fix null reference exception on new books

app/src/main/java/org/sil/bloom/reader/WiFi/NewBookListenerService.java, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/16)
=> BL-4754 Display sending computer IP and name if available

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/17)
=> BL-4755 Notice new book from WiFi

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java, app/src/main/java/org/sil/bloom/reader/WiFi/NewBookListenerService.java, app/src/main/res/values/strings.xml
...and do send own device name to desktop for display
...hence message body is now JSON
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/21)
=> BL-4857 Don't display desktop IP address

app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/WiFi/NewBookListenerService.java
Corresponding fix for Bloom must be merged first!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/20)
=> BL-4864 look for version embedded in bloomd

app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java, app/src/main/res/layout/activity_get_from_wi_fi.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/22)
=> BL-4869 Auto-scroll progress box in WiFi receive

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/res/layout/activity_reader.xml
Basic display of animation while loading.
Make browsers for pages lazily
Make their contents just hold a single page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/18)
=> BL-4883 speed up opening book

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/24)
=> BL-4913 don't remove regular click handler on long click

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
(Try to coordinate merge with corresponding desktop commit)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/23)
=> BL-4908 Remove book folder layer in bloomd

app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java, app/src/main/java/org/sil/bloom/reader/WiFi/NewBookListenerService.java
Including a kludge to get around an Android bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/28)
=> BL-4755 Get notifications of new books reliably

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/31)
=> BL-4944 handle trying to open a book externally deleted

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
(provided there's just one htm file in folder)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/32)
=> BL-4946 Handle htm file different from bloomd name

app/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/33)
=> BL-4945 Build Bloom in multiple flavors

app/src/main/res/raw/about_bloom.txt, app/src/main/res/raw/about_reader.txt, app/src/main/res/raw/about_sil.txt, app/src/main/res/raw/release_notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/35)
=> Content for various menus

README.md, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java, app/src/main/res/anim/grow_and_fade.xml, app/src/main/res/drawable/pause_on_circle.xml, app/src/main/res/drawable/play_on_circle.xml, app/src/main/res/layout/activity_reader.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/39)
=> BL-4756 BloomPlayer (talking book) support

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/40)
=> Merge 'JohnThomson/BL-4955analytics' with some improvements (BL-4956)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/36)
=> BL-4955 push analytics information to Segment.io

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/42)
=> User must initiate all page turns (BL-5067)

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/layout/activity_get_from_wi_fi.xml, app/src/main/res/values/styles.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/45)
=> Adhere to Material Design in dialogs (BL-5092)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/46)
=> Prevent play/pause when user is attempting page turn (BL-5068)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
And distinguish ones narrated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/48)
=> BL-5082 report actual pages read

app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/java/org/sil/bloom/reader/models/ExtStorageUnavailableException.java, app/src/main/java/org/sil/bloom/reader/models/SampleBookLoader.java, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/49)
=>  BL-5085 Verify External Media is mounted when we access our books directory

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/50)
=> Fix the filename generated for a bloom book imported from the SD card root with the system file explorer

app/src/main/java/org/sil/bloom/reader/SharingManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/52)
=> BL-5112 Share book using Uri.fromFile for ShareIt and Super Beam

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java, app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/54)
=> BL-5097 enhance filter to ignore tags for non-existent shelves

app/src/main/java/org/sil/bloom/reader/ShelfActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/57)
=> Check for and handle case where OS has destroyed book collection

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/58)
=> BL-5108 include branding with book analytics

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/res/layout/book_list_content.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/60)
=> BL-4765 Show book thumbnails in list

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/62)
=> BL-4972 Lock Wifi during file transfer

app/src/main/assets/book support files/assets.css, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
Requires BloomPlayer changes, which should be merged first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/64)
=> BL-5109 Pan/Zoom animation

app/src/main/res/layout/activity_main.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/67)
=> Fix menu item color for Android 8.0 (BL-5207)

app/src/main/play/en-US/listing/fulldescription, app/src/main/res/raw/release_notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/73)
=> Update release notes (BL-5210)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/77)
=> BL-5203 question analytics

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/80)
=> BL-5103 add analytics for lang, book finished, total pages

app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/83)
=> BL-5251 reword WiFi receive command

app/src/main/res/layout/book_list_content.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/84)
=> Larger thumbnails, vertically centered titles, a bit tighter rows BL-5325

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/85)
=> BL-5331 send count of CQs with page load/read event

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
Not a real pull request so much as a proof of concept. When we decide to support embedded video for real, these are the basic additions the Android side will need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/86)
=> [BL-5275] Embedded video proof of concept.

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
…h happens on the quiz page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/87)
=> [BL-5275] Guard against null currentView in stopAndStartvideos() which happens on the quiz page.

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/88)
=> BL-5375 Show CQs before back matter

app/build.gradle, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/89)
=> BL-5404 Play background audio

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/92)
=> BL-5531 fix crash on books with audio and CQs

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/90)
=> [BL-5407] Allow bookshelves to be nested.

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/97)
=>  Fix for BL-5555 and caching images

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/94)
=> Bl 5537 Force CQ pages to portrait orientation.

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/98)
=> [BL-5569] Show a helpful error when a book fails to open because the storage is full

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/101)
=> [BL-5673] Don't allow paused state to persist between books.

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/ShareBooksDialogFragment.java, app/src/main/java/org/sil/bloom/reader/SharingManager.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
https://issues.bloomlibrary.org/youtrack/issue/BL-5501
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/105)
=> [BL-5501] Share a whole shelf as a bloombundle from the longpress menu

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/res/layout/question_page.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/106)
=> [BL-5603] Fix bug in CQ landscape layout.

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/values/strings.xml
https://issues.bloomlibrary.org/youtrack/issue/BL-5711
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/107)
=> [BL-5711] Delete an entire bookshelf.

README.md, app/src/main/play/en-US/listing/fulldescription, app/src/main/res/raw/release_notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/111)
=> Update Play Store description, release notes, and README.md

app/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/112)
=> Promote master to Version 1.2

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/ThumbnailCleanup.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
https://silbloom.myjetbrains.com/youtrack/issue/BL-5726
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/109)
=> [BL-5726] Support .jpg book thumbnails as well as .png

app/src/main/java/org/sil/bloom/reader/ThumbnailCleanup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/113)
=> [BL-5726] Fix path error in thumbnail cleanup

app/src/main/java/org/sil/bloom/reader/BookAdapter.java, app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java, app/src/main/res/layout/app_bar_main.xml, app/src/main/res/layout/book_list_content.xml, app/src/main/res/layout/content_main.xml, app/src/main/res/values/colors.xml
https://silbloom.myjetbrains.com/youtrack/issue/BL-5716
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/108)
=> [BL-5716] Improve performance by using ReyclerView for Book List

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/114)
=> BL-5585 Bloom Features

app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/116)
=> BL-5805 don't highlight sentences which have no actual audio file

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/120)
=> Fix NullPointerException reported in Play console

app/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/127)
=> Make MissingTranslation lint issue be a warning rather than fatal

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/129)
=> Clean-up no-op code from MainActivity.

app/build.gradle, app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/130)
=> Upgrade to gradle 4.4

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/131)
=> Fix null pointer (reported in Play console)

app/build.gradle, app/src/androidTest/java/org/sil/bloom/reader/AndroidTestHelper.java, app/src/androidTest/java/org/sil/bloom/reader/ReadMoonAndCapTest.java
Add an integration test that opens Moon and Cap, verifies the title and the first page, and interacts with the first CQ.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/137)
=> Android Integration Test: ReadMoonAndCapTest.

app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/BookFinderTask.java, app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/res/layout/book_list_content.xml, app/src/main/res/layout/content_main.xml, app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/values/strings.xml
https://issues.bloomlibrary.org/youtrack/issue/BL-5791
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/119)
=> [BL-5791] File search

app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/res/values/strings.xml
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/141)
=> [BL-6596] Include books in Bloom folder of SD card in the book collection

app/src/main/AndroidManifest.xml
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-5969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/139)
=> [BL-5969] Rework intent filters for receiving bloom files.

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/142)
=> [BL-6644] Change name of Bloom folder on sd card to BloomExternal.

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/BookFinderTask.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/143)
=> [BL-6608] Import bloomshelves in File Search.

app/src/main/assets/book support files/assets.css
Needs a parallel fix to BloomPlayer which should be merged first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/146)
=> BL-6650 Fix narration highlight for text box audio

app/src/main/java/org/sil/bloom/reader/BundleTask.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/ShareAllBooksDialogFragment.java, app/src/main/java/org/sil/bloom/reader/ShareBooksDialogFragment.java, app/src/main/java/org/sil/bloom/reader/ShareShelfDialogFragment.java, app/src/main/java/org/sil/bloom/reader/SharingManager.java, app/src/main/res/layout/dialog_share_books.xml
* Also switched to the support library DialogFragment since the other one is now deprecated.
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/147)
=> [BL-6598] Show a progress spinner while creating bloom bundles.

app/src/main/java/org/sil/bloom/reader/MainActivity.java
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-6521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/148)
=> [BL-6521] Fix button color for Delete Shelf dialog.

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
* getting multimedia state of page from js
* get play/pause to work with video playback
and ignore play/pause if page isn't multimedia
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/150)
=> BL-6693/6695 Pause/Play Video

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/151)
=> Prevent two NullPointerExceptions which showed up on the Play Console

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
* tap anywhere now toggles system bars
showing/hiding as well as pause/play of media
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/152)
=> BL-6696 toggle full-screen mode

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WiFi/SyncServer.java
* determination of "multimedia" forgot to include
video
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/153)
=> BL-6693 Fix pause

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/154)
=> BL-6693 Add animation to multimedia detection

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java, app/src/main/res/drawable/ic_speaker.xml, app/src/main/res/layout/book_list_content.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/155)
=> BL-5879 Add symbol to thumb if audio exists

app/src/main/assets/book support files/assets.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/160)
=> Remove focus rectangle (orange border) (BL-6849)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/161)
=> Delay automatic playback of video for one second (BL-6984)

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/163)
=> Update README.md with instructions for setting up to build (20190322)

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/164)
=> Prevent NullPointerException created during Play Console pre-launch testing

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/MainActivity.java
* opens .bloomd from Dropbox and FileManager
* doesn't open other .zip files
* random .zip file renamed as .bloomd gets Cannot open file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/162)
=> BL-6941 Handle files better

app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/165)
=> Prevent playing previous page's sound file (BL-6925)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/166)
=> Reset videos when changing pages (BL-7004)

app/src/main/java/org/sil/bloom/reader/IOUtilities.java
It's my hypothesis that older devices are more susceptible to the
problem addressed here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/168)
=> Make importing big books more reliable on old devices (BL-6970)

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
Also removed a method that isn't used anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/169)
=> Prevent invalid bloomd file from crashing Bloom Reader (BL-6970)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/167)
=> Toggle video pause/play on actual playing or not (BL-7003)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/173)
=> Fix display of system menu when book is playing (BL-6974)

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/BookFinderTask.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/171)
=> Deal with file transfer appending .enc to .bloomd filenames (BL-7044)

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/174)
=> Tell user when renaming an invalid book (BL-6970)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/176)
=> Fix hide/show system menu for async delay in pause/resume (BL-6974)

app/src/main/AndroidManifest.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/179)
=> Allow Gmail to open .bloomd and .bloombundle files (BL-6941)

app/src/main/AndroidManifest.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/180)
=> Allow Drive to open .bloomd files on newer devices (BL-6941)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/181)
=> BL-7019 Skip pages marked data-bloomreader="2" or later

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/182)
=> Always show navigation bar; never show status (notification) bar (BL-6998)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/183)
=> Never show status bar in Reader Activity (BL-6998)

.gitignore, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/184)
=> Fix play/pause icons to show appropriately (BL-7251)

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/185)
=> Prevent NullPointerException seen on Play Console

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/186)
=> BL-7256 Include some book features in analytics report

app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/187)
=> BL-7257 Add event to report source of installation

app/src/alpha/play/en-US/listing/title, app/src/beta/play/en-US/listing/title
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/188)
=> Change store listing to BR Alpha/Beta (BL-7232)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
Report playing an audio page only for pages that have audio (and when not paused...that was already true)
Report on every pause (but only count since last pause)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/189)
=> BL-7317 improvements to pages-read reporting

app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/190)
=> BL-7257 send install attributed event even if 'unknown'

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/191)
=> BL-7255 improve naming of new audio video duration properties

app/src/main/java/org/sil/bloom/reader/Quiz.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/192)
=> Fix quiz question numbering for Bloom Reader 1.x (BL-7267)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/193)
=> BL-7334 Don't count xmatter pages in analytics

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/194)
=> BL-7337 Set WebView font size to 100%

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/195)
=> BL-7317 Prevent counting page after audio as audio

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/196)
=> BL-7346 Report pages read when finished; add sessionId

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/199)
=> BL-7255 and BL-7317 fixes to audio analytics

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/200)
=> Fix pages read count in nonMultimedia books (BL-7425)

app/src/main/java/org/sil/bloom/reader/ShelfActivity.java, app/src/main/res/layout/book_list_content.xml, app/src/main/res/layout/content_main.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/values/colors.xml
* will now handle large font size better
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/198)
=> BL-7337 Title screen layout fix

app/src/main/java/org/sil/bloom/reader/ImportBundleTask.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/values-bn/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
* if bloombundle file appears to be corrupt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/197)
=> BL-7370 Add message on import

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
[WIP] is waiting on reply to comment question
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/202)
=> BL-7376 Add orig copyright holder to analytics

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
* This bit was accidentally removed before merging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/203)
=> BL-7376 Fix to Add Copyright Holder

app/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/205)
=> Upgrade to SDK 28 (BL-7421)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/208)
=> BL-7544 Use Bloom-Player API 1.0

app/src/androidTest/java/org/sil/bloom/reader/AndroidTestHelper.java, app/src/androidTest/java/org/sil/bloom/reader/ReadMoonAndCapTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/210)
=> Update instrumentation tests to handle web-based quiz (BL-7515)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/ReportAnalyticsTask.java, app/src/main/java/org/sil/bloom/reader/ReportAnalyticsTaskParams.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/212)
=> BL-7380 See if sending analytics asynchronously improves reliability

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/213)
=> Stop audio when returning to book list; also attempt pause/resume (BL-7580)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/214)
=> Show/hide the navigation bar based on user interaction (BL-7516)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
* needs bloom-player PR first
* get book properties from bloom-player
- canRotate
- landscape
* if book is not marked 'canRotate', set orientation
to match book setting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/215)
=> BL-7536 Fix auto-rotate

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/217)
=> BL-7535 allow video playback without user gesture; hide placeholder

app/src/main/java/org/sil/bloom/reader/WebAppInterface.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/218)
=> BL-7255 kludge to prevent utterly implausible audio durations

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This should be merged after the corresponding bloom-player change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/219)
=> Tell bloom-player to pause/resume when ReaderActivity does (BL-7580)

app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/InitializeLibraryTask.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/TextFileContent.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/res/values/strings.xml
Users may still have to wait for all the books to be loaded, but there's
some sign of work being done rather than a possibly frozen device.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/221)
=> Run BookCollection.init() asynchronously and add progress bar (BL-7432)

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/222)
=> BL-7890 Make failure to import more visible

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/224)
=> Fix a test compile error introduced earlier (BL-7432)

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/223)
=> Rename HTML file extracted from bloomd to index.htm (BL-7816)

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/SetBookListItemViewExtrasTask.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/225)
=> Prevent race condition between thumbnails and book opening (BL-7813)

app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/226)
=> Simplify initial loading progress message (BL-7432)

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/227)
=> Prevent one more race condition (BL-7813)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
Note that this is on the Version1.3 branch.  The master branch already behaves properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/228)
=> Allow music to play whenever it exists (BL-7447)

app/src/main/java/org/sil/bloom/reader/IOUtilities.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/229)
=> BL-7538 Enable sharing of long names

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/230)
=> Don't copy books from BloomExternal to Bloom during Find (BL-7128)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/231)
=> Don't let user font setting affect book display (BL-8101)

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/232)
=> Prevent crash when .bloomd is loaded before app is run (BL-8218)

app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/ReaderWebChromeClient.java
- don't consider books invalid if they have extra html files in folders
- toast if error occurs in activity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/233)
=> Support HTML widgets (iframe activities)

app/src/main/java/org/sil/bloom/reader/InitializeLibraryTask.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/234)
=> Handle invalid bloomd files gracefully again (BL-8437)

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/235)
=> Make various things in BookCollection thread-safe (BL-8647)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
* depends on BP update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/237)
=> BL-8458 Add vertical centering

app/src/androidTest/java/org/sil/bloom/reader/models/BookCollectionTest.java, app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java, app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/238)
=> Display book title from metadata instead of filename (BL-8674)

app/src/main/java/org/sil/bloom/reader/models/AlphanumComparator.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java, app/src/test/java/org/sil/bloom/reader/models/BookOrShelfTest.java
* allow collections with numeric prefixes to sort correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/239)
=> BL-8689 Natural book ordering

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/ReportAnalyticsTask.java, app/src/main/java/org/sil/bloom/reader/ReportAnalyticsTaskParams.java, app/src/main/java/org/sil/bloom/reader/Settings.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/241)
=> Add gps location to analytics

app/build.gradle, app/src/androidTest/java/org/sil/bloom/reader/ReadMoonAndCapTest.java, app/src/main/java/org/sil/bloom/reader/ReportAnalyticsTask.java
* tried to make it a bit less flaky too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/242)
=> Fix failing Moon and Cap test

app/src/main/java/org/sil/bloom/reader/wifi/AcceptFileHandler.java, app/src/main/java/org/sil/bloom/reader/wifi/GetFromWiFiActivity.java, app/src/main/java/org/sil/bloom/reader/wifi/NewBookListenerService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/244)
=> Show all new books after "receiving books from computer" (BL-8793)

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/245)
=> Don't highlight books imported from a bloombundle (BL-8808)

app/src/main/java/org/sil/bloom/reader/ReportAnalyticsTask.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/247)
=> Add explicit provider location values to analytic reports (BL-8821)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/249)
=> Hide bloom-player's full screen button (BL-8834)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/250)
=> Add distribution source analytics (BL-8873)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/252)
=> Prepare for bloom-player being able to send analytics itself (BL-8874)

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/254)
=> Don't crash if the device doesn't have GPS

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/255)
=> [2.2] BL-8992 Tweak BR permission message

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
Untested because I cannot replicate the scenario
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/258)
=> Prevent duplicates when installing downloads (BL-9637)

app/src/main/java/org/sil/bloom/reader/FileCleanupTask.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/test/java/org/sil/bloom/reader/IOUtilitiesTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/259)
=> Fix file delete on Android 10+ (BL-9637)

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/Settings.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/260)
=> Add book read duration to analytics (BL-10230)

app/src/main/java/org/sil/bloom/reader/EnsureStatsSentAsyncTask.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/values-bn/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa-rAF/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-mam/strings.xml, app/src/main/res/values-my/strings.xml, app/src/main/res/values-pbu/strings.xml, app/src/main/res/values-prs/strings.xml, app/src/main/res/values-ps-rAF/strings.xml, app/src/main/res/values-quc/strings.xml, app/src/main/res/values-sw/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
with John Thomson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/261)
=> Add menu item indicating status of sending analytics (BL-10229)

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/262)
=> Properly handle OnNewIntent the second time

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/263)
=> Clean up a couple exceptions seen in Play console

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/264)
=> Handle new intent without file permissions (BL-10230)

app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/SharingManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/267)
=> When sharing (possibly with older version of BR), use .bloomd (BL-10036)

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/268)
=> Fix problem with recursive directories and SAF (BL-10327)

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/SetBookListItemViewExtrasTask.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/265)
=> More tidying up Android 11 fixes (BL-8651)

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/269)
=> Automatically read books from private SD folder (BL-10490)

app/src/main/java/org/sil/bloom/reader/models/BookCollection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/270)
=> Fix bookshelves after errant merge (BL-10568)

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/menu/activity_main_drawer.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/273)
=> Remove the "Find Bloom books on this device" command entirely

app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/274)
=> Don't act like we have any legacy permissions on Android 12+

app/src/main/java/org/sil/bloom/reader/MainActivity.java
With JT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/276)
=> Make file migration more robust (BL-10863)

app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/FileCleanupTask.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java, app/src/main/java/org/sil/bloom/reader/wifi/AcceptFileHandler.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/277)
=> Fix USB transfer (BL-10870)

app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/values/strings.xml
with JT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/278)
=> Add "Find lost books" menu item (BL-10863)

app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/SAFUtilities.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/279)
=> Fix deviceId.json processing (BL-10880)

app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/280)
=> Improvements for handling deviceId.json (BL-10880)

app/src/main/java/org/sil/bloom/reader/AnalyticsDeviceInfoEntryDialogFragment.java, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/layout/dialog_device_info.xml, app/src/main/res/menu/activity_main_drawer.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/281)
=> Add form for entering device info for analytics (BL-10880)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/282)
=> Leave it to Bloom Player to provide distribution info (BL-8898)

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/java/org/sil/bloom/reader/ReaderWebViewClient.java, app/src/main/java/org/sil/bloom/reader/ZipFileOrUri.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/283)
=> Extract files from bloomPub as needed (BL-11128)

app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/NeedNewerWebViewActivity.java, app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, app/src/main/res/layout/activity_need_newer_web_view2.xml, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/284)
=> Warn the user if an old WebView is installed (BL-11176)

app/src/main/java/org/sil/bloom/reader/NeedNewerWebViewActivity.java, app/src/main/res/layout/activity_need_newer_web_view2.xml, app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/285)
=> Add Restart button to upgrade webview warning (BL-11176)

app/src/main/java/org/sil/bloom/reader/BloomLibraryActivity.java, app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, app/src/main/res/layout/content_main.xml, app/src/main/res/values/strings.xml
Also tweak text to lower case, support for closing keyboad
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/288)
=> Fix get-more-books button at bottom of screen

app/src/main/java/org/sil/bloom/reader/DownloadsView.java, app/src/main/java/org/sil/bloom/reader/ZipFileOrUri.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/289)
=> Don't crash when trying to download an invalid .bloomPUB (BL-11420)

app/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/290)
=> Upgrade Segment SDK (BL-11380)

app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/292)
=> Don't let Play store automated tests skew analytics (BL-11422)

app/src/main/java/org/sil/bloom/reader/BloomLibraryActivity.java, app/src/main/res/drawable/ic_baseline_home_24.xml, app/src/main/res/menu/bloom_library_menu.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/293)
=> Add home button to Bloom Library view (BL-11419)

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/BloomLibraryActivity.java, app/src/main/res/xml/network_security_config.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/294)
=> Add blorg back buttons (BL-11408)

app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/295)
=> Open Book Detail link in external browser (BL-11409)

README.md, app/src/main/java/org/sil/bloom/reader/BloomLibraryActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/296)
=> Switch blorg host based on channel (BL-11409)

app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/297)
=> Fix book download (BL-11409)

app/src/main/java/org/sil/bloom/reader/DownloadProgressView.java
...in download-in-progress dialog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/299)
=> Convert all plus signs to spaces, even groups of three (BL-11446)

app/src/main/java/org/sil/bloom/reader/BloomLibraryActivity.java, app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java, app/src/main/res/xml/network_security_config.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/300)
=> Allow server to gzip responses in BloomLibraryActivity

app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/301)
=> Stop blocking Bloom Library analytics (BL-11423)

app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/302)
=> Fix more places Bloom shows file names with plus signs (BL-11446)

app/src/main/java/org/sil/bloom/reader/BloomLibraryActivity.java, app/src/main/java/org/sil/bloom/reader/DownloadsView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/303)
=> Make analytics events for downloading a book (BL-11423)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/CommonUtilities.java, app/src/main/java/org/sil/bloom/reader/DownloadsView.java, app/src/main/java/org/sil/bloom/reader/IOUtilities.java, app/src/main/java/org/sil/bloom/reader/NeedNewerWebViewActivity.java, app/src/main/java/org/sil/bloom/reader/SharingManager.java, app/src/main/res/raw/about_reader.txt, build.gradle, gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/298)
=> Target Api 33, Android 13 (BL-11181)

app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/304)
=> Fix external blorg link for Android <=6 (BL-11409)

app/src/main/java/org/sil/bloom/reader/BloomLibraryActivity.java, app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/305)
=> Stop implementing shouldInterceptRequest to fix blorg-in-BR (BL-11181)

app/src/main/java/org/sil/bloom/reader/ReaderActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/306)
=> Require Webview 54 (BL-11623)

app/src/main/java/org/sil/bloom/reader/BaseActivity.java, app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, app/src/main/java/org/sil/bloom/reader/DownloadsView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader/307)
=> Report location with new Download Book event (BL-11636)

app/src/main/java/org/sil/bloom/reader/BookReadyView.java, app/src/main/java/org/sil/bloom/reader/DownloadsView.java, app/src/main/java/org/sil/bloom/reader/SAFUtilities.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/308)
=> Fix some crashes seen in the Play console

app/src/main/java/org/sil/bloom/reader/MainActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/311)
=> Fix import of .bloombundle and .bloomshelf on newer Androids (BL-13392)

app/build.gradle, app/src/androidTest/java/org/sil/bloom/reader/ReadMoonAndCapTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/org/sil/bloom/reader/DownloadsView.java, app/src/main/java/org/sil/bloom/reader/wifi/GetFromWiFiActivity.java, app/src/main/res/raw/about_reader.txt, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/312)
=> Target Android 14, SDK 34 (BL-13663)

app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, app/src/main/java/org/sil/bloom/reader/SetBookListItemViewExtrasTask.java, app/src/main/java/org/sil/bloom/reader/models/AlphanumComparator.java, app/src/main/java/org/sil/bloom/reader/models/BookOrShelf.java, app/src/test/java/org/sil/bloom/reader/models/BookOrShelfTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/316)
=> Use title to sort books rather than file name (BL-14289)

app/src/main/java/org/sil/bloom/reader/ReaderWebViewClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/318)
=> Fix widget loading by fixing shouldOverrideUrlLoading (BL-14626)

app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/java/org/sil/bloom/reader/SharingManager.java, gradle.properties
Unfortunately, I haven't yet found a fix for the bug that specifically prevents sharing "The Moon and the Cap."
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/320)
=> Added support for sharing multiple books/shelves at once (BL-14392)

app/src/main/java/org/sil/bloom/reader/MainActivity.java
…14406)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/321)
=> Add current Bloom Reader version to the top of the about popup

app/build.gradle, app/src/main/java/org/sil/bloom/reader/MainActivity.java, app/src/main/res/layout/nav_header_main.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomReader/322)
=> Added bloom player version info to menu (BL-14373)
